---
- name: Assures .drush dir exists in each home directory
  file: 
    path: /home/{{ app_env['user'] }}/.drush 
    state: directory
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
  
- name: Create Drush aliases (current, build and source)
  template:
    src: aliases.drushrc.php.j2
    dest: /home/{{ app_env['user'] }}/.drush/{{ app_name }}.aliases.drushrc.php
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
