---
- name: Assures .drush dir exists in each home directory
  file: 
    path: /home/{{ app['website']['user'] }}/.drush 
    state: directory
    owner: "{{ app['website']['user'] }}"
    group: "{{ app['website']['group'] }}"
  
- name: Create Drush aliases (current, build and source)
  template:
    src: drush/aliases.drushrc.php.j2
    dest: /home/{{ item['user'] }}/.drush/{{ app['website']['host'] }}.aliases.drushrc.php
    owner: "{{ app['website']['user'] }}"
    group: "{{ app['website']['group'] }}"
