---
- name: Install drush
  composer:
    arguments: "drush/drush:^{{ drush_min_version }}"
    command: require
    working_dir: /usr/share/composer
  notify: drush cc drush

- name: Install drush/config-extra
  composer:
    arguments: "drush/config-extra"
    command: require
    working_dir: /usr/share/composer
  when: app_drupal_version|version_compare('8', '==')
  notify: drush cc drush

- name: Make drush available globally
  file:
    src: /usr/share/composer/vendor/bin/drush
    dest: /usr/bin/drush
    state: link
    force: no

- name: Enable drush autocomplete feature system-wide
  file:
    src: /usr/share/composer/vendor/bin/drush.complete.sh
    dest: /etc/bash_completion.d/drush
    state: link
    force: no

- name: Enable drush autocomplete feature for the current session
  shell: "source /etc/bash_completion.d/drush"
  args:
    executable: /bin/bash
  changed_when: false
