---
- name: Assures .drush dir exists in each home directory
  file: 
    path: /home/{{ app_env['user'] }}/.drush 
    state: directory
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"

- name: Download the site_audit, hacked, coder, registry_rebuild and drush_language modules
  command: drush dl "{{ item }}" --destination=/home/"{{ app_env['user'] }}"/.drush/"{{ item }}" --yes 
    creates=/home/"{{ app_env['user'] }}"/.drush/"{{ item }}"
  with_items:
  - site_audit
  - hacked
  - coder
  - registry_rebuild
  - drush_language
  notify: drush cc drush
  become: "{{ app_env['user'] }}"