---
- name: drush | download the site audit module
  command: drush dl site_audit --destination=/home/{{ item['user'] }}/.drush/site_audit --yes 
    creates=/home/{{ item['user'] }}/.drush/site_audit
  notify: drush cc drush
  with_items: vhost_sites

- name: drush | download the hacked module
  command: drush dl hacked --destination=/home/{{ item['user'] }}/.drush/hacked --yes 
    creates=/home/{{ item['user'] }}/.drush/hacked
  notify: drush cc drush
  with_items: vhost_sites

- name: drush | download the Coder module
  command: drush dl coder-7.x-2.x --destination=/home/{{ item['user'] }}/.drush/coder --yes 
    creates=/home/{{ item['user'] }}/.drush/coder
  notify: drush cc drush
  with_items: vhost_sites

- name: drush | download the Registry Rebuild module
  command: drush dl registry_rebuild --destination=/home/{{ item['user'] }}/.drush/registry_rebuild --yes 
    creates=/home/{{ item['user'] }}/.drush/registry_rebuild
  notify: drush cc drush
  with_items: vhost_sites
  